### ISSUE TITLE
Incluir links de Instalação e Atualização no header dos userscripts

### ISSUE THREAD

**Issue by rn4n** [stackuserflow/stackoverflow-tampermonkey-greasemonkey#1]
Gostaria de propor que fosse incluído o link de instalação e update no cabeçalho dos user scripts. Da forma como estão atualmente, um usuário só teria acesso as melhorias e correções caso instalasse o script novamente.

A ideia é incluir os valores abaixo, apontados para o arquivo raw aqui no GitHub:
 ```
// @downloadURL <url>
// @updateURL   <url>
```

Ficando, por exemplo, para o script [cleansochat-user.js][1]: 
```
// ==UserScript==
// @name         CleanChat
// @namespace    stackuserflow
// @version      0.1.7
// @description  Muda o visual do chat para algo mais simples
// @author       Guilherme Nascimento (https://github.com/brcontainer)
// @match        *://chat.stackoverflow.com/rooms/*
// @match        *://chat.stackexchange.com/rooms/*
// @exclude      *://chat.stackoverflow.com/rooms/info/*
// @exclude      *://chat.stackexchange.com/rooms/info/*
// @grant        none
// @downloadURL  https://github.com/stackuserflow/stackoverflow-tampermonkey-greasemonkey/raw/master/CleanChat.user.js
// @updateURL    https://github.com/stackuserflow/stackoverflow-tampermonkey-greasemonkey/raw/master/CleanChat.user.js
// ==/UserScript==
```

Outra sugestão é alterar todos os "botões" install do README, apontando-os para o arquivo raw dos scripts. De acordo com a documentação do Tampermonkey e GreaseMonkey, qualquer script terminado em `.user.js` será lido como um possível user script. Fica até mais fácil para os usuários instalarem/atualizarem, faça o teste:

https://github.com/stackuserflow/stackoverflow-tampermonkey-greasemonkey/raw/master/CleanChat.user.js

[1]:https://github.com/stackuserflow/stackoverflow-tampermonkey-greasemonkey/blob/master/CleanChat.user.js

**Comment by brcontainer** [comment]
@reebr obrigado, creio que esteja tudo corrigido agora https://github.com/stackuserflow/stackoverflow-tampermonkey-greasemonkey/commit/0b09ce6f92850853b45a433adee6c16bb54420e9
